// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGi7tNKxdgZzhDuU7IrPOQs8PCNkCenU',
    appId: '1:1060341231975:web:933f8f4c457f3669f7bfc2',
    messagingSenderId: '1060341231975',
    projectId: 'dyeus-authentication-system',
    authDomain: 'dyeus-authentication-system.firebaseapp.com',
    storageBucket: 'dyeus-authentication-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCU4BgX2sBeVoX_o5aux0f4M149ibsZA',
    appId: '1:1060341231975:android:4a8d93b6b31e2583f7bfc2',
    messagingSenderId: '1060341231975',
    projectId: 'dyeus-authentication-system',
    storageBucket: 'dyeus-authentication-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvcuQdIKJ-qkLqgdcqHIzLM3o5P8itus',
    appId: '1:1060341231975:ios:6620368aa10be769f7bfc2',
    messagingSenderId: '1060341231975',
    projectId: 'dyeus-authentication-system',
    storageBucket: 'dyeus-authentication-system.appspot.com',
    androidClientId: '1060341231975-k7i3g8hn4vqml8j2vsfk2ae5na7ofelg.apps.googleusercontent.com',
    iosClientId: '1060341231975-o9s1i1c4c3hfkt4d60g2jdph300f002l.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyeusAuthenticationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvcuQdIKJ-qkLqgdcqHIzLM3o5P8itus',
    appId: '1:1060341231975:ios:6620368aa10be769f7bfc2',
    messagingSenderId: '1060341231975',
    projectId: 'dyeus-authentication-system',
    storageBucket: 'dyeus-authentication-system.appspot.com',
    androidClientId: '1060341231975-k7i3g8hn4vqml8j2vsfk2ae5na7ofelg.apps.googleusercontent.com',
    iosClientId: '1060341231975-o9s1i1c4c3hfkt4d60g2jdph300f002l.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyeusAuthenticationSystem',
  );
}
